name: saitama_trash_data_tool
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  file_picker:
  logger:
  excel:
  csv:
  intl:
  hooks_riverpod:
  flutter_hooks:
  riverpod_annotation:
  web:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  riverpod_generator:
  build_runner:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
